databases:
  - name: think_postgresql
    databaseName: render_deploy
    user: nw
    region: singapore
    ipAllowList: []

services:
  - type: web
    name: guru_mail_tests
    plan: free
    region: singapore
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: think_postgresql
          property: connectionString

